[project]
name = "sydney-bus-reliability"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32",
    "aws-lambda-powertools>=3.0",
    "boto3>=1.35",
    "gtfs-realtime-bindings>=1.0",
    "pyarrow==24.0.0",
    "duckdb>=1.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3",
    "pytest-cov>=6.0",
    "moto[s3,ssm]>=5.0",
    "responses>=0.25",
    "mypy>=1.13",
    "pylint>=3.3",
    "isort>=5.13",
    "types-requests",
    "boto3-stubs[s3]>=1.35",
    "numpydoc>=1.11.0",
    "pyarrow-stubs>=20.0.0.20260819",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 79

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src --cov-report=term-missing"

[tool.mypy]
python_version = "3.14"
strict = true

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",  # don't require "Examples" section
    "SA01",  # don't require "See Also" section
    "ES01",  # don't require extended summary
]
exclude = [
    "\\.__init__$",
]
